---
# Usage:
#   ansible-playbook apt-update_pb.yml --limit <HOSTS>
# Optional: reboot=true to reboot if required (default: true)
- name: Update & upgrade server(s)
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot the server (if required)
      ansible.builtin.reboot:
      when:
        - reboot_required_file.stat.exists
        - reboot | default(true) | bool
