---
# Playbook takes 2 variables. Run playbook with: --extra-vars="nodes=<HOST(S)>, package=<PACKAGE>"
- name: Remove package on server(s)
  become: true
  hosts: "{{ nodes }}"

  tasks:
  - name: Remove {{ package }}
    apt:
      name: "{{ package }}"
      state: absent
