---
# Playbook takes 2 variables. Run playbook with: --extra-vars="nodes=<HOST(S)>, package=<PACKAGE>"
- name: Install package on server(s)
  become: true
  hosts: "{{ nodes }}"

  tasks:
  - name: Install {{ package }}
    apt:
      name: "{{ package }}"
      state: present
      update_cache: true
      cache_valid_time: 3600 # Updates the cache  if the current cache is built 3600 seconds(1 hour)
