---
# Usage:
#   ansible-playbook reboot_pb.yml --limit <HOSTS>
- name: Reboot server(s)
  hosts: all
  become: true

  tasks:
    - name: Reboot host
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
      register: reboot_result

    - name: Validate reboot
      ansible.builtin.assert:
        that: reboot_result.rebooted
        fail_msg: "Reboot failed on {{ inventory_hostname }}"
        quiet: true
