---
- name: Reboot server(s)
  hosts: "{{ nodes }}"
  become: true
  become_user: root
  tasks:
    - name: Rebooting {{ nodes }}
      ansible.builtin.reboot:
        msg: "Machine is going down for a reboot - Reboot initiated by Ansible"
      register: reboot_result

    - name: Validate reboot
      assert:
        that: reboot_result.rebooted == true
        # Checks if the reboot was successful
