---
- name: Shutdown servers @flems.dk
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
        msg: "Shutdown initiated by Ansible"
