---
# Usage:
#   ansible-playbook shutdown_pb.yml --limit <HOSTS>
- name: Shutdown server(s)
  hosts: all
  become: true

  tasks:
    - name: Shutdown host
      community.general.shutdown:
        msg: "Shutdown initiated by Ansible"
